version: '3'
services:
  loo-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
      - "80:80"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
      - "27018:27018"
    volumes:
      - "/opt/mongodb:/data/db"
